# Generated by Django 4.1.7 on 2023-04-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=124)),
                ('last_name', models.CharField(max_length=124)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=214)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=124)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=124)),
                ('id_number', models.IntegerField()),
                ('current_location', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=214)),
                ('phone_no', models.CharField(max_length=20)),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media/images')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('HEATH & BEAUTY', 'Heathy & Beauty'), ('FURNITURE', 'Furniture'), ('CULTERY', 'Cultery'), ('BEDDINGS', 'Beddings'), ('CLOTHING & EQUIPMENT', 'Clothing & Equipment'), ('FRUITS & VEGETABLES', 'Fruits & Vegetables'), ('SPORTS & ARTS', 'Sports & Arts'), ('VEHICLES', 'Vehicles'), ('EQUIPMENT & CONSTRUCTION', 'Equipment & Construction'), ('GRAINS', 'Grains'), ('OTHERS', 'Others')], default='Others', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=254)),
                ('model', models.CharField(blank=True, max_length=254)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default=None, max_length=124)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_for_sale', to='EASE_MARKET.seller')),
            ],
        ),
    ]
